services:
  - type: web
    name: tb-api-backend
    env: python
    runtime: python-3.11     # ✅ Explicitly pin Python 3.11
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ACCOUNT1_ADMIN_USER
        sync: false
      - key: ACCOUNT1_ADMIN_PASS
        sync: false
      - key: ACCOUNT2_ADMIN_USER
        sync: false
      - key: ACCOUNT2_ADMIN_PASS
        sync: false
      - key: TB_ACCOUNTS
        sync: false
      - key: TB_SCHEDULER_INTERVAL
        value: "30"
